--change the container to work in the PDB that was created by default with the Oracle Express installation
ALTER SESSION SET CONTAINER = XEPDB1;

--create a user/schema to have your own “personal space” in the XEPDB1 pluggable database
CREATE USER SCHOOL_KAUR_2211871 IDENTIFIED BY 123; --use your own password instead of abc.

--grant the permission to SCHOOL_KAUR_2211871 to connect and create objects (tables, etc.)
GRANT CONNECT, RESOURCE TO SCHOOL_KAUR_2211871;

--give the permission to SCHOOL_KAUR_2211871 to also write data in the tables
GRANT UNLIMITED TABLESPACE TO SCHOOL_KAUR_2211871;

--after that step, you can create a connection on the XEPDB1 database with the user SCHOOL_KAUR_2211871 and password 123, and start working in your own schema

ALTER SESSION SET CURRENT_SCHEMA=SCHOOL_KAUR_2211871;    

--------------------------------------------------------
--  File created - Thursday-November-02-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type TYPE_STUDENT_ROW
--------------------------------------------------------    


  CREATE OR REPLACE EDITIONABLE TYPE "SCHOOL_KAUR_2211871"."TYPE_STUDENT_ROW" AS OBJECT 
(  
    STUDENTID	VARCHAR2(32 BYTE),
    LASTNAME	VARCHAR2(25 BYTE),
    FIRSTNAME	VARCHAR2(25 BYTE),
    ADDRESS	VARCHAR2(50 BYTE),
    CITY	VARCHAR2(20 BYTE),
    POSTALCODE	VARCHAR2(10 BYTE),
    STUDENTNUMBER   VARCHAR2(9 BYTE),
    CREATEDDATE TIMESTAMP(6),
    LASTMODIFIEDDATE	TIMESTAMP(6)
)

/
--------------------------------------------------------
--  DDL for Type TYPE_STUDENT_TABLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCHOOL_KAUR_2211871"."TYPE_STUDENT_TABLE" 
AS TABLE OF TYPE_STUDENT_ROW;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED TYPE STUDENT TABLE.

/
--------------------------------------------------------
--  DDL for Type TYPE_TEACHER_ROW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCHOOL_KAUR_2211871"."TYPE_TEACHER_ROW" AS OBJECT 
( 
TEACHERID	VARCHAR2(32 BYTE)
,LASTNAME	VARCHAR2(25 BYTE)
,FIRSTNAME	VARCHAR2(25 BYTE)
,EMAIL	VARCHAR2(20 BYTE)
,SALARY	NUMBER(4,2)
,CREATEDDATE	TIMESTAMP(6)
,LASTMODIFIEDDATE	TIMESTAMP(6) 
)

/
--------------------------------------------------------
--  DDL for Type TYPE_TEACHER_TABLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCHOOL_KAUR_2211871"."TYPE_TEACHER_TABLE" 
AS TABLE OF TYPE_TEACHER_ROW;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED TYPE TEACHER TABLE.

/
--------------------------------------------------------
--  DDL for Table COURSES
--------------------------------------------------------

  CREATE TABLE "SCHOOL_KAUR_2211871"."COURSES" 
   (	"COURSEID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"COURSENAME" VARCHAR2(25 BYTE), 
	"COURSECODE" VARCHAR2(10 BYTE), 
	"COURSEDESCRIPTION" VARCHAR2(4000 BYTE), 
	"CREATEDDATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"LASTMODIFIEDDATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "SCHOOL_KAUR_2211871"."COURSES"  IS '2023-10-30	Harsharan Kaur(2211871)	Created the COURSES table.
2023-10-30	Harsharan Kaur(2211871)	Added the column COURSEID.
2023-10-30	Harsharan Kaur(2211871)	Added the column COURSENAME.
2023-10-30	Harsharan Kaur(2211871)	Added the column COURSECODE.
2023-10-30	Harsharan Kaur(2211871)	Added the column COURSEDESCRIPTION.
2023-10-30	Harsharan Kaur(2211871)	Added the column CREATEDDATE.
2023-10-30	Harsharan Kaur(2211871)	Added the column LASTMODIFIEDDATE.
';
--------------------------------------------------------
--  DDL for Table REPORTS
--------------------------------------------------------

  CREATE TABLE "SCHOOL_KAUR_2211871"."REPORTS" 
   (	"REPORTID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"STUDENTID" VARCHAR2(32 BYTE), 
	"TEACHERID" VARCHAR2(32 BYTE), 
	"RESULT" NUMBER(3,0), 
	"COMMENTS" VARCHAR2(250 BYTE), 
	"CREATEDDATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"LASTMODIFIEDDATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "SCHOOL_KAUR_2211871"."REPORTS"  IS 'REPORTS:
2023-10-30	Harsharan Kaur(2211871)	Created the REPORTS table.
2023-10-30	Harsharan Kaur(2211871)	Added the column REPORTID.
2023-10-30	Harsharan Kaur(2211871)	Added the column STUDENTID.
2023-10-30	Harsharan Kaur(2211871)	Added the column TEACHERID.
2023-10-30	Harsharan Kaur(2211871)	Added the column RESULT.
2023-10-30	Harsharan Kaur(2211871)	Added the column COMMENTS.
2023-10-30	Harsharan Kaur(2211871)	Added the column CREATEDDATE.
2023-10-30	Harsharan Kaur(2211871)	Added the column LASTMODIFIEDDATE.';
--------------------------------------------------------
--  DDL for Table STUDENTS
--------------------------------------------------------

  CREATE TABLE "SCHOOL_KAUR_2211871"."STUDENTS" 
   (	"STUDENTID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"LASTNAME" VARCHAR2(25 BYTE), 
	"FIRSTNAME" VARCHAR2(25 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"POSTALCODE" VARCHAR2(10 BYTE), 
	"STUDENTNUMBER" VARCHAR2(9 BYTE), 
	"CREATEDDATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"LASTMODIFIEDDATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "SCHOOL_KAUR_2211871"."STUDENTS"  IS 'STUDENTS:
2023-10-30	Harsharan Kaur(2211871)	Created the STUDENTS table.
2023-10-30	Harsharan Kaur(2211871)	Added the column STUDENTID.
2023-10-30	Harsharan Kaur(2211871)	Added the column LASTNAME.
2023-10-30	Harsharan Kaur(2211871)	Added the column FIRSTNAME.
2023-10-30	Harsharan Kaur(2211871)	Added the column ADDRESS.
2023-10-30	Harsharan Kaur(2211871)	Added the column CITY.
2023-10-30	Harsharan Kaur(2211871)	Added the column POSTALCODE.
2023-10-30	Harsharan Kaur(2211871)	Added the column CREATEDDATE.
2023-10-30	Harsharan Kaur(2211871)	Added the column LASTMODIFIEDDATE.
';
--------------------------------------------------------
--  DDL for Table TEACHERS
--------------------------------------------------------

  CREATE TABLE "SCHOOL_KAUR_2211871"."TEACHERS" 
   (	"TEACHERID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"LASTNAME" VARCHAR2(25 BYTE), 
	"FIRSTNAME" VARCHAR2(25 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"SALARY" NUMBER(4,2), 
	"CREATEDDATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"LASTMODIFIEDDATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "SCHOOL_KAUR_2211871"."TEACHERS"  IS 'TEACHERS:
2023-10-30	Harsharan Kaur(2211871)	Created the TEACHERS table.
2023-10-30	Harsharan Kaur(2211871)	Added the column TEACHERID.
2023-10-30	Harsharan Kaur(2211871)	Added the column LASTNAME.
2023-10-30	Harsharan Kaur(2211871)	Added the column FIRSTNAME.
2023-10-30	Harsharan Kaur(2211871)	Added the column EMAIL.
2023-10-30	Harsharan Kaur(2211871)	Added the column SALARY.
2023-10-30	Harsharan Kaur(2211871)	Added the column CREATEDDATE.
2023-10-30	Harsharan Kaur(2211871)	Added the column LASTMODIFIEDDATE.
';
REM INSERTING into SCHOOL_KAUR_2211871.COURSES
SET DEFINE OFF;
Insert into SCHOOL_KAUR_2211871.COURSES (COURSEID,COURSENAME,COURSECODE,COURSEDESCRIPTION,CREATEDDATE,LASTMODIFIEDDATE) values ('DA02A192F3C84B73BD4169FAEC4A1098','OOP','AB23','SEM1-COURSE',to_timestamp('02-11-23 7:57:19.119000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('02-11-23 7:57:19.119000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
Insert into SCHOOL_KAUR_2211871.COURSES (COURSEID,COURSENAME,COURSECODE,COURSEDESCRIPTION,CREATEDDATE,LASTMODIFIEDDATE) values ('81164644412B461596619E005E556512','DATABASE','AB12','SEM2-COURSE',to_timestamp('02-11-23 7:57:19.127000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('02-11-23 7:57:19.127000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
Insert into SCHOOL_KAUR_2211871.COURSES (COURSEID,COURSENAME,COURSECODE,COURSEDESCRIPTION,CREATEDDATE,LASTMODIFIEDDATE) values ('275AF885B6C34755A34BA710E96BC897','WEB DEVELOPMENT','AB13','SEM3-COURSE',to_timestamp('02-11-23 7:57:19.130000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('02-11-23 7:57:19.130000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
REM INSERTING into SCHOOL_KAUR_2211871.REPORTS
SET DEFINE OFF;
Insert into SCHOOL_KAUR_2211871.REPORTS (REPORTID,STUDENTID,TEACHERID,RESULT,COMMENTS,CREATEDDATE,LASTMODIFIEDDATE) values ('A1EC19DDA97C4691AFD86B9D234376A1','E031DC7071004CEDA383BF03C6E78736','E30593D4E95F405A8A44DE456CD6E29C',90,'PASS',to_timestamp('02-11-23 4:04:27.143000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('02-11-23 4:04:27.143000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
Insert into SCHOOL_KAUR_2211871.REPORTS (REPORTID,STUDENTID,TEACHERID,RESULT,COMMENTS,CREATEDDATE,LASTMODIFIEDDATE) values ('6DEE818CA9F44796BC13D8366B75A9B2','C106A56DFCB14305988EA8D3A2521AF9','5D9A53AABC9C4BE196937652DB69004B',80,'PASS',to_timestamp('02-11-23 4:06:03.724000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('02-11-23 4:06:03.724000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
Insert into SCHOOL_KAUR_2211871.REPORTS (REPORTID,STUDENTID,TEACHERID,RESULT,COMMENTS,CREATEDDATE,LASTMODIFIEDDATE) values ('C0B78847C53C40D0A5A2C79FFDF12FBF','FBB77796234342B695DA4B070CEE5420','7056DCDA9BF24C4592DC65900C9E476D',50,'FAIL',to_timestamp('02-11-23 4:07:47.331000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('02-11-23 4:07:47.331000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
REM INSERTING into SCHOOL_KAUR_2211871.STUDENTS
SET DEFINE OFF;
Insert into SCHOOL_KAUR_2211871.STUDENTS (STUDENTID,LASTNAME,FIRSTNAME,ADDRESS,CITY,POSTALCODE,STUDENTNUMBER,CREATEDDATE,LASTMODIFIEDDATE) values ('E031DC7071004CEDA383BF03C6E78736','KAUR','HARSHARAN','1255 DU FORT','NONTREAL','H3H2NC','100',to_timestamp('02-11-23 3:48:31.505000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('02-11-23 3:48:31.505000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
Insert into SCHOOL_KAUR_2211871.STUDENTS (STUDENTID,LASTNAME,FIRSTNAME,ADDRESS,CITY,POSTALCODE,STUDENTNUMBER,CREATEDDATE,LASTMODIFIEDDATE) values ('C106A56DFCB14305988EA8D3A2521AF9','KAUR','MANPREET','1212 ST MATHEU','TORONTO','H2H3NG','101',to_timestamp('02-11-23 3:48:31.515000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('02-11-23 3:48:31.515000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
Insert into SCHOOL_KAUR_2211871.STUDENTS (STUDENTID,LASTNAME,FIRSTNAME,ADDRESS,CITY,POSTALCODE,STUDENTNUMBER,CREATEDDATE,LASTMODIFIEDDATE) values ('FBB77796234342B695DA4B070CEE5420','PATEL','VIRAJ','2001 ST CATHERIENE','OTTAWA','3H2BK','102',to_timestamp('02-11-23 3:48:31.517000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('02-11-23 3:48:31.517000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
REM INSERTING into SCHOOL_KAUR_2211871.TEACHERS
SET DEFINE OFF;
Insert into SCHOOL_KAUR_2211871.TEACHERS (TEACHERID,LASTNAME,FIRSTNAME,EMAIL,SALARY,CREATEDDATE,LASTMODIFIEDDATE) values ('E30593D4E95F405A8A44DE456CD6E29C','SHARMA','JOE','joe123@gmail.com',55,to_timestamp('02-11-23 3:52:16.334000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('02-11-23 3:52:16.334000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
Insert into SCHOOL_KAUR_2211871.TEACHERS (TEACHERID,LASTNAME,FIRSTNAME,EMAIL,SALARY,CREATEDDATE,LASTMODIFIEDDATE) values ('5D9A53AABC9C4BE196937652DB69004B','BING','MONICA','monica23@gmail.com',27,to_timestamp('02-11-23 3:52:16.341000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('02-11-23 3:52:16.341000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
Insert into SCHOOL_KAUR_2211871.TEACHERS (TEACHERID,LASTNAME,FIRSTNAME,EMAIL,SALARY,CREATEDDATE,LASTMODIFIEDDATE) values ('7056DCDA9BF24C4592DC65900C9E476D','GREEN','RACHEL','rachel45@gmail.com',50,to_timestamp('02-11-23 3:52:16.344000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('02-11-23 3:52:16.344000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
--------------------------------------------------------
--  DDL for Index TEACHERS_UK_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_KAUR_2211871"."TEACHERS_UK_EMAIL" ON "SCHOOL_KAUR_2211871"."TEACHERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_KAUR_2211871"."STUDENTS_PK" ON "SCHOOL_KAUR_2211871"."STUDENTS" ("STUDENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REPORTS_INDEX_TEACHER_ID
--------------------------------------------------------

  CREATE INDEX "SCHOOL_KAUR_2211871"."REPORTS_INDEX_TEACHER_ID" ON "SCHOOL_KAUR_2211871"."REPORTS" ("TEACHERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REPORTS_INDEX_STUDENT_ID
--------------------------------------------------------

  CREATE INDEX "SCHOOL_KAUR_2211871"."REPORTS_INDEX_STUDENT_ID" ON "SCHOOL_KAUR_2211871"."REPORTS" ("STUDENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENTS_INDEX_STUDENT_NUMBER
--------------------------------------------------------

  CREATE INDEX "SCHOOL_KAUR_2211871"."STUDENTS_INDEX_STUDENT_NUMBER" ON "SCHOOL_KAUR_2211871"."STUDENTS" ("STUDENTNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEACHER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_KAUR_2211871"."TEACHER_PK" ON "SCHOOL_KAUR_2211871"."TEACHERS" ("TEACHERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COURSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_KAUR_2211871"."COURSES_PK" ON "SCHOOL_KAUR_2211871"."COURSES" ("COURSEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COURSES_INDEX_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_KAUR_2211871"."COURSES_INDEX_CODE" ON "SCHOOL_KAUR_2211871"."COURSES" ("COURSECODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_KAUR_2211871"."REPORT_PK" ON "SCHOOL_KAUR_2211871"."REPORTS" ("REPORTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_MODIFY_COURSES_DATE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHOOL_KAUR_2211871"."TRIGGER_MODIFY_COURSES_DATE" 
BEFORE UPDATE ON COURSES 
FOR EACH ROW 
BEGIN
    -- WHEN UPDATE EXECUTES ,IT WILL UPDATE LASTMODIFYDATE COLUMN.
    :NEW.LASTMODIFIEDDATE := CURRENT_TIMESTAMP;
END;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED TRIGGER MODIFY COURSE DATE.
/
ALTER TRIGGER "SCHOOL_KAUR_2211871"."TRIGGER_MODIFY_COURSES_DATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_MODIFY_DATE_REPORT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHOOL_KAUR_2211871"."TRIGGER_MODIFY_DATE_REPORT" 
BEFORE UPDATE ON REPORTS
FOR EACH ROW 
BEGIN
    -- WHEN UPDATE EXECUTES ,IT WILL UPDATE LASTMODIFYDATE COLUMN.
    :NEW.LASTMODIFIEDDATE := CURRENT_TIMESTAMP;
END;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED TRIGGER MODIFY DATE REPORT.
/
ALTER TRIGGER "SCHOOL_KAUR_2211871"."TRIGGER_MODIFY_DATE_REPORT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_MODIFY_DATE_STUDENTS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHOOL_KAUR_2211871"."TRIGGER_MODIFY_DATE_STUDENTS" 
BEFORE UPDATE ON STUDENTS  
FOR EACH ROW 
BEGIN
    -- WHEN UPDATE EXECUTES ,IT WILL UPDATE LASTMODIFYDATE COLUMN.
    :NEW.LASTMODIFIEDDATE := CURRENT_TIMESTAMP;
END;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED TRIGGER MODIFY DATE STUDENTS.
/
ALTER TRIGGER "SCHOOL_KAUR_2211871"."TRIGGER_MODIFY_DATE_STUDENTS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_MODIFY_DATE_TEACHERS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHOOL_KAUR_2211871"."TRIGGER_MODIFY_DATE_TEACHERS" 
BEFORE UPDATE ON TEACHERS 
FOR EACH ROW 
BEGIN
    -- WHEN UPDATE EXECUTES ,IT WILL UPDATE LASTMODIFYDATE COLUMN.
    :NEW.LASTMODIFIEDDATE := CURRENT_TIMESTAMP;
END;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED TRIGGER MODIFY TEACHERS DATE.
/
ALTER TRIGGER "SCHOOL_KAUR_2211871"."TRIGGER_MODIFY_DATE_TEACHERS" ENABLE;
--------------------------------------------------------
--  DDL for Procedure PROCEDURE_DELETE_TEACHERS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_KAUR_2211871"."PROCEDURE_DELETE_TEACHERS" 
(PARAM_TEACHERID IN VARCHAR2 
) AS 
BEGIN
   --DELETE A ROW FROM THE TEACHERS TABLE
    DELETE FROM TEACHERS
    WHERE TEACHERID = PARAM_TEACHERID;
END PROCEDURE_DELETE_TEACHERS;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED PROCEDURE DELETE

/
--------------------------------------------------------
--  DDL for Procedure PROCEDURE_STUDENTS_DELETE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_KAUR_2211871"."PROCEDURE_STUDENTS_DELETE" 
(PARAM_STUDENTID IN VARCHAR2 
) AS 
BEGIN
   --DELETE A ROW FROM THE STUDENTS TABLE
    DELETE FROM STUDENTS 
    WHERE STUDENTID = PARAM_STUDENTID;
END PROCEDURE_STUDENTS_DELETE;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED PROCEDURE DELETE

/
--------------------------------------------------------
--  DDL for Procedure PROCEDURE_STUDENT_INSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_KAUR_2211871"."PROCEDURE_STUDENT_INSERT" 
(
  PARAM_LASTNAME IN VARCHAR2 
, PARAM_FIRSTNAME IN VARCHAR2 
, PARAM_ADDRESS IN VARCHAR2 
, PARAM_CITY IN VARCHAR2 
, PARAM_POSTALCODE IN VARCHAR2
, PARAM_STUDENTNUMBER IN VARCHAR2 
) AS 
BEGIN
    -- Insert a new row into students table.
    INSERT INTO STUDENTS(LASTNAME, FIRSTNAME, ADDRESS, CITY, POSTALCODE, STUDENTNUMBER)
    VALUES(PARAM_LASTNAME, PARAM_FIRSTNAME, PARAM_ADDRESS, PARAM_CITY, PARAM_POSTALCODE, PARAM_STUDENTNUMBER);
END PROCEDURE_STUDENT_INSERT;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED PROCEDURE INSERT.

/
--------------------------------------------------------
--  DDL for Procedure PROCEDURE_TEACHER_INSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_KAUR_2211871"."PROCEDURE_TEACHER_INSERT" 
(

 PARAM_LASTNAME	IN VARCHAR2
,PARAM_FIRSTNAME IN	VARCHAR2
,PARAM_EMAIL IN	VARCHAR2
,PARAM_SALARY IN NUMBER
)AS 
BEGIN
  -- Inserting a new row into Teacher table.
    INSERT INTO TEACHERS(LASTNAME, FIRSTNAME, EMAIL, SALARY)
    VALUES(PARAM_LASTNAME, PARAM_FIRSTNAME, PARAM_EMAIL, PARAM_SALARY);

END PROCEDURE_TEACHER_INSERT;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED PROCEDURE INSERT

/
--------------------------------------------------------
--  DDL for Procedure PROCEDURE_UPDATE_STUDENTS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_KAUR_2211871"."PROCEDURE_UPDATE_STUDENTS" 
(
  PARAM_STUDENTID IN VARCHAR2
, PARAM_LASTNAME IN VARCHAR2 
, PARAM_FIRSTNAME IN VARCHAR2 
, PARAM_ADDRESS IN VARCHAR2 
, PARAM_CITY IN VARCHAR2 
, PARAM_POSTALCODE IN VARCHAR2
, PARAM_STUDENTNUMBER IN VARCHAR2 
) AS 
BEGIN
    -- Update a row into students table.
    UPDATE students SET LASTNAME = PARAM_LASTNAME, FIRSTNAME = PARAM_FIRSTNAME, ADDRESS = PARAM_ADDRESS, 
    CITY = PARAM_CITY, POSTALCODE = PARAM_POSTALCODE, STUDENTNUMBER = PARAM_STUDENTNUMBER
    WHERE studentid = param_studentid;
END PROCEDURE_UPDATE_STUDENTS;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED PROCEDURE UPDATE.

/
--------------------------------------------------------
--  DDL for Procedure PROCEDURE_UPDATE_TEACHERS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_KAUR_2211871"."PROCEDURE_UPDATE_TEACHERS" 
(PARAM_TEACHERID IN VARCHAR2
,PARAM_LASTNAME	IN VARCHAR2
,PARAM_FIRSTNAME IN	VARCHAR2
,PARAM_EMAIL IN	VARCHAR2
,PARAM_SALARY IN NUMBER)
AS 
BEGIN
     -- Update a row into TEACHERS table.
    UPDATE TEACHERS SET LASTNAME= PARAM_LASTNAME, FIRSTNAME = PARAM_FIRSTNAME, EMAIL = PARAM_EMAIL, 
    SALARY = PARAM_SALARY
    WHERE TEACHERID = PARAM_TEACHERID;
END PROCEDURE_UPDATE_TEACHERS;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED PROCEDURE UPDATE.

/
--------------------------------------------------------
--  DDL for Function STUDENT_SELECT_ALL_ROWS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHOOL_KAUR_2211871"."STUDENT_SELECT_ALL_ROWS" 
RETURN TYPE_STUDENT_TABLE PIPELINED AS 
BEGIN
    --loop for each row in the table
    FOR each_row IN (SELECT STUDENTID, LASTNAME, FIRSTNAME, 
                    ADDRESS, CITY, POSTALCODE, CREATEDDATE, LASTMODIFIEDDATE, STUDENTNUMBER
                    FROM STUDENTS 
                    ORDER BY STUDENTNUMBER)
    -- Begin of the loop.
    LOOP
        PIPE ROW
                (
                    TYPE_STUDENT_ROW
                    (   each_row.STUDENTID, each_row.STUDENTNUMBER, each_row.LASTNAME, 
                        each_row.FIRSTNAME, each_row.ADDRESS, each_row.CITY, 
                        each_row.POSTALCODE, each_row.CREATEDDATE, 
                        each_row.LASTMODIFIEDDATE
                    )
                );
    -- END of the loop.
    END LOOP;
 
    RETURN;
END STUDENT_SELECT_ALL_ROWS;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED FUNCTION SELECT ALL ROWS.

/
--------------------------------------------------------
--  DDL for Function STUDENT_SELECT_ONE_ROWS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHOOL_KAUR_2211871"."STUDENT_SELECT_ONE_ROWS" 
(
    PARAM_STUDENTID IN VARCHAR2
)
RETURN TYPE_STUDENT_TABLE PIPELINED AS 
BEGIN
    --loop for each row in the table
    FOR each_row IN (SELECT STUDENTID, LASTNAME, FIRSTNAME, 
                    ADDRESS, CITY, POSTALCODE, CREATEDDATE, LASTMODIFIEDDATE, STUDENTNUMBER
                    FROM STUDENTS 
                    WHERE STUDENTID = PARAM_STUDENTID
                    )
                    
    -- Begin of the loop.
    LOOP
        PIPE ROW
                (
                    TYPE_STUDENT_ROW
                    (   each_row.STUDENTID, each_row.STUDENTNUMBER, each_row.LASTNAME, 
                        each_row.FIRSTNAME, each_row.ADDRESS, each_row.CITY, 
                        each_row.POSTALCODE, each_row.CREATEDDATE, 
                        each_row.LASTMODIFIEDDATE
                    )
                );
    -- END of the loop.
    END LOOP;

    RETURN;
END STUDENT_SELECT_ONE_ROWS;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED FUNCTION SELECT ONE ROW.

/
--------------------------------------------------------
--  DDL for Function TEACHER_SELECT_ALL_ROWS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHOOL_KAUR_2211871"."TEACHER_SELECT_ALL_ROWS" 
RETURN TYPE_TEACHER_TABLE PIPELINED AS 
BEGIN
    --loop for each row in the table
    FOR each_row IN (SELECT TEACHERID, LASTNAME, FIRSTNAME, EMAIL, SALARY,
                    CREATEDDATE, LASTMODIFIEDDATE
                    FROM TEACHERS 
                    ORDER BY LASTNAME)
    -- Begin of the loop.
    LOOP
        PIPE ROW
                (
                    TYPE_TEACHER_ROW
                    (   each_row.TEACHERID, each_row.LASTNAME, each_row.FIRSTNAME,
                        each_row.EMAIL, each_row.SALARY, each_row.CREATEDDATE,
                        each_row.LASTMODIFIEDDATE
                    )
                );
    -- END of the loop.
    END LOOP;

    RETURN;
    --RETURN NULL;
END TEACHER_SELECT_ALL_ROWS;
--2023-11-01 HARSHARAN KAUR(2211871) CREATED FUNCTION SELECT ALL ROWS.

/
--------------------------------------------------------
--  DDL for Function TEACHER_SELECT_ONE_ROW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHOOL_KAUR_2211871"."TEACHER_SELECT_ONE_ROW" 
(
  PARAM_TEACHERID VARCHAR2
)
RETURN TYPE_TEACHER_TABLE PIPELINED AS 
BEGIN
    --loop for each row in the table
    FOR each_row IN (SELECT TEACHERID, LASTNAME, FIRSTNAME, EMAIL, SALARY,
                    CREATEDDATE, LASTMODIFIEDDATE
                    FROM TEACHERS 
                    WHERE TEACHERID=PARAM_TEACHERID)
    -- Begin of the loop.
    LOOP
        PIPE ROW
                (
                    TYPE_TEACHER_ROW
                    (   each_row.TEACHERID, each_row.LASTNAME, each_row.FIRSTNAME,
                        each_row.EMAIL, each_row.SALARY, each_row.CREATEDDATE,
                        each_row.LASTMODIFIEDDATE
                    )
                );
    -- END of the loop.
    END LOOP;
    --2023-11-01 HARSHARAN KAUR(2211871) CREATED FUNCTION SELECT ONE ROW.

    RETURN;
END TEACHER_SELECT_ONE_ROW;

/
--------------------------------------------------------
--  Constraints for Table REPORTS
--------------------------------------------------------

  ALTER TABLE "SCHOOL_KAUR_2211871"."REPORTS" ADD CHECK (Result >= 0 AND Result <= 100) ENABLE;
  ALTER TABLE "SCHOOL_KAUR_2211871"."REPORTS" ADD CONSTRAINT "REPORT_PK" PRIMARY KEY ("REPORTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHOOL_KAUR_2211871"."REPORTS" MODIFY ("STUDENTID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."REPORTS" MODIFY ("TEACHERID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."REPORTS" MODIFY ("RESULT" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."REPORTS" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."REPORTS" MODIFY ("LASTMODIFIEDDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENTS
--------------------------------------------------------

  ALTER TABLE "SCHOOL_KAUR_2211871"."STUDENTS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."STUDENTS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."STUDENTS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."STUDENTS" MODIFY ("POSTALCODE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."STUDENTS" MODIFY ("STUDENTNUMBER" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."STUDENTS" ADD CONSTRAINT "STUDENTS_PK" PRIMARY KEY ("STUDENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHOOL_KAUR_2211871"."STUDENTS" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."STUDENTS" MODIFY ("LASTMODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."STUDENTS" ADD CONSTRAINT "STUDENTS_UK_STUDENT_NUMBER" UNIQUE ("STUDENTNUMBER")
  USING INDEX "SCHOOL_KAUR_2211871"."STUDENTS_INDEX_STUDENT_NUMBER"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEACHERS
--------------------------------------------------------

  ALTER TABLE "SCHOOL_KAUR_2211871"."TEACHERS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."TEACHERS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."TEACHERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."TEACHERS" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."TEACHERS" ADD CONSTRAINT "TEACHER_PK" PRIMARY KEY ("TEACHERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHOOL_KAUR_2211871"."TEACHERS" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."TEACHERS" MODIFY ("LASTMODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."TEACHERS" ADD CONSTRAINT "TEACHERS_UK_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHOOL_KAUR_2211871"."TEACHERS" ADD CONSTRAINT "TEACHERS_CHK_SALARY" CHECK (SALARY>=0) ENABLE;
--------------------------------------------------------
--  Constraints for Table COURSES
--------------------------------------------------------

  ALTER TABLE "SCHOOL_KAUR_2211871"."COURSES" MODIFY ("COURSENAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."COURSES" MODIFY ("COURSECODE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."COURSES" ADD CONSTRAINT "COURSES_PK" PRIMARY KEY ("COURSEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHOOL_KAUR_2211871"."COURSES" ADD CONSTRAINT "COURSES_UK_COURSE_CODE" UNIQUE ("COURSECODE")
  USING INDEX (CREATE UNIQUE INDEX "SCHOOL_KAUR_2211871"."COURSES_INDEX_CODE" ON "SCHOOL_KAUR_2211871"."COURSES" ("COURSECODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "SCHOOL_KAUR_2211871"."COURSES" MODIFY ("COURSEDESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."COURSES" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_KAUR_2211871"."COURSES" MODIFY ("LASTMODIFIEDDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REPORTS
--------------------------------------------------------

  ALTER TABLE "SCHOOL_KAUR_2211871"."REPORTS" ADD CONSTRAINT "REPORT_FK_STUDENT_ID" FOREIGN KEY ("STUDENTID")
	  REFERENCES "SCHOOL_KAUR_2211871"."STUDENTS" ("STUDENTID") ENABLE;
  ALTER TABLE "SCHOOL_KAUR_2211871"."REPORTS" ADD CONSTRAINT "REPORT_FK_TEACHER_ID" FOREIGN KEY ("TEACHERID")
	  REFERENCES "SCHOOL_KAUR_2211871"."TEACHERS" ("TEACHERID") ENABLE;
