SET SERVEROUTPUT ON;
--1-PROCEDURE_INSERT_REPORTS
DECLARE
  PARAM_STUDENTID VARCHAR2(200);
  PARAM_TEACHERID VARCHAR2(200);
  PARAM_RESULT NUMBER;
  PARAM_COMMENTS VARCHAR2(200);
  PARAM_EXAM_DATE DATE;
  PARAM_NUMBER_OF_EXAMS_DONE NUMBER;
BEGIN

  PARAM_STUDENTID := 'C106A56DFCB14305988EA8D3A2521AF9';
  PARAM_TEACHERID := '7056DCDA9BF24C4592DC65900C9E476D';
  PARAM_RESULT := 30;
  PARAM_COMMENTS := 'FAIL';
  PARAM_EXAM_DATE := to_date('23-11-23','yyyy-MM-dd');

  PROCEDURE_INSERT_REPORTS(
    PARAM_STUDENTID => PARAM_STUDENTID,
    PARAM_TEACHERID => PARAM_TEACHERID,
    PARAM_RESULT => PARAM_RESULT,
    PARAM_COMMENTS => PARAM_COMMENTS,
    PARAM_EXAM_DATE => PARAM_EXAM_DATE,
    PARAM_NUMBER_OF_EXAMS_DONE => PARAM_NUMBER_OF_EXAMS_DONE
  );
    
    DBMS_OUTPUT.PUT_LINE('PARAM_NUMBER_OF_EXAMS_DONE = ' || PARAM_NUMBER_OF_EXAMS_DONE);
    
END;
/
--2-PROCEDURE INSERT_COURSES_RETURN_COURSEID
DECLARE
  PARAM_COURSEID VARCHAR2(200);
  PARAM_COURSENAME VARCHAR2(200);
  PARAM_COURSECODE VARCHAR2(200);
  PARAM_COURSEDESCRIPTION VARCHAR2(200);
BEGIN
  PARAM_COURSENAME := 'MS Word';
  PARAM_COURSECODE := 'MS15';
  PARAM_COURSEDESCRIPTION := 'SEM4-COURSE';

  INSERT_COURSES_RETURN_COURSEID(
    PARAM_COURSEID => PARAM_COURSEID,
    PARAM_COURSENAME => PARAM_COURSENAME,
    PARAM_COURSECODE => PARAM_COURSECODE,
    PARAM_COURSEDESCRIPTION => PARAM_COURSEDESCRIPTION
  );
  
DBMS_OUTPUT.PUT_LINE('PARAM_COURSEID = ' || PARAM_COURSEID);

  
DBMS_OUTPUT.PUT_LINE('PARAM_COURSENAME = ' || PARAM_COURSENAME);
END;
/
--3-PROCEDURE_DELETE_COURSES
DECLARE
  PARAM_COURSEID VARCHAR2(200);
BEGIN
  PARAM_COURSEID := '275AF885B6C34755A34BA710E96BC897';

  PROCEDURE_DELETE_COURSES(
    PARAM_COURSEID => PARAM_COURSEID
  ); 
END;
/
--4-PROCEDURE_STUDENT_INSERT
DECLARE
  PARAM_LASTNAME VARCHAR2(200);
  PARAM_FIRSTNAME VARCHAR2(200);
  PARAM_ADDRESS VARCHAR2(200);
  PARAM_CITY VARCHAR2(200);
  PARAM_POSTALCODE VARCHAR2(200);
  PARAM_STUDENTNUMBER VARCHAR2(200);
  PARAM_EXAM_TRIES NUMBER;
  PARAM_ALLERGIES VARCHAR2(200);
BEGIN
  PARAM_LASTNAME := 'Dil';
  PARAM_FIRSTNAME := 'Rohan';
  PARAM_ADDRESS := 'Du fort';
  PARAM_CITY := 'Montreal';
  PARAM_POSTALCODE := '2B3 4B2';
  PARAM_STUDENTNUMBER := NULL;
  PARAM_EXAM_TRIES := 1;
  PARAM_ALLERGIES := 'peanuts';

  PROCEDURE_STUDENT_INSERT(
    PARAM_LASTNAME => PARAM_LASTNAME,
    PARAM_FIRSTNAME => PARAM_FIRSTNAME,
    PARAM_ADDRESS => PARAM_ADDRESS,
    PARAM_CITY => PARAM_CITY,
    PARAM_POSTALCODE => PARAM_POSTALCODE,
    PARAM_STUDENTNUMBER => PARAM_STUDENTNUMBER,
    PARAM_EXAM_TRIES => PARAM_EXAM_TRIES,
    PARAM_ALLERGIES => PARAM_ALLERGIES
  );
   
DBMS_OUTPUT.PUT_LINE('PARAM_ALLERGIES = ' || PARAM_ALLERGIES);

END;
/
--5-PROCEDURE_UPDATE_STUDTENTS
DECLARE
  PARAM_STUDENTID VARCHAR2(200);
  PARAM_LASTNAME VARCHAR2(200);
  PARAM_FIRSTNAME VARCHAR2(200);
  PARAM_ADDRESS VARCHAR2(200);
  PARAM_CITY VARCHAR2(200);
  PARAM_POSTALCODE VARCHAR2(200);
  PARAM_STUDENTNUMBER VARCHAR2(200);
  PARAM_EXAM_TRIES NUMBER;
  PARAM_ALLERGIES VARCHAR2(200);
BEGIN
  PARAM_STUDENTID := 'FBB77796234342B695DA4B070CEE5420';
  PARAM_LASTNAME := 'SINGH';
  PARAM_FIRSTNAME := 'SAM';
  PARAM_ADDRESS := '12 ST MATHEU';
  PARAM_CITY := 'ONTARIO';
  PARAM_POSTALCODE := 'H21 1D2';
  PARAM_STUDENTNUMBER := '132';
  PARAM_EXAM_TRIES := NULL;
  PARAM_ALLERGIES := 'Peanuts';

  PROCEDURE_UPDATE_STUDENTS(
    PARAM_STUDENTID => PARAM_STUDENTID,
    PARAM_LASTNAME => PARAM_LASTNAME,
    PARAM_FIRSTNAME => PARAM_FIRSTNAME,
    PARAM_ADDRESS => PARAM_ADDRESS,
    PARAM_CITY => PARAM_CITY,
    PARAM_POSTALCODE => PARAM_POSTALCODE,
    PARAM_STUDENTNUMBER => PARAM_STUDENTNUMBER,
    PARAM_EXAM_TRIES => PARAM_EXAM_TRIES,
    PARAM_ALLERGIES => PARAM_ALLERGIES
  );
 
DBMS_OUTPUT.PUT_LINE('PARAM_ALLERGIES = ' || PARAM_ALLERGIES); 
END;
/
--6-PROCEDURE_STUDENTS_DELETE
DECLARE
  PARAM_STUDENTID VARCHAR2(200);
BEGIN
  PARAM_STUDENTID := 'F6C4F734AF5E4C5C9B5F54F215FFC219';

  PROCEDURE_STUDENTS_DELETE(
    PARAM_STUDENTID => PARAM_STUDENTID
  );
--rollback; 
END;
/
--7-STUDENT_SELECT_ONE_ROW
SELECT * FROM STUDENT_SELECT_ONE_ROWS('E031DC7071004CEDA383BF03C6E78736');

--8-STUDENT_SELECT_ALL_ROW
SELECT * FROM STUDENT_SELECT_ALL_ROWS();

--9-FUNCTION TEACHER_CALCULATE_PAYCHECK
SELECT TEACHER_CALCULATE_PAYCHECK(20,2,10) FROM DUAL;

--10-FUNCTION TIMESHEET_JOIN_TEACHERS_SELECT_ALL_ROWS
SELECT * FROM TIMESHEETS_JOIN_TEACHERS_SELECT_ALL_ROWS('E30593D4E95F405A8A44DE456CD6E29C');
